apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    # image: alpine:3.22
    image: ghcr.io/usagi-flow/kube-acme:latest-amd64
    command: ["tail", "-f", "/dev/null"]