apiVersion: v1
kind: Service
metadata:
  name: garage
  labels:
    app: garage
spec:
  selector:
    app: garage
  ports:
    - name: s3-api
      port: 3900
      targetPort: s3-api
    - name: rpc
      port: 3901
      targetPort: rpc
    - name: s3-web
      port: 3902
      targetPort: s3-web
    - name: admin
      port: 3903
      targetPort: admin
    - name: k2v-api
      port: 3904
      targetPort: k2v-api